### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by KEVINR1169** [CODEMAX666/BlockingURL#1]
Hello,
While testing your code, I found an issue.
I am using BlueStack emulator and not working properly. 
What is the solution of this issue?

**Comment by CODEMAX666** [comment]
Hello,
Thanks for getting in touch.
Let me check that for you.
Have you granted root access in Bluestacks? To perform the URL blocking action, root access is required

**Comment by CODEMAX666** [comment]
Please check and ping me afterward.
